# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tobro-top-100

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_42212c1c91704b2190e66500eb508b71 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4a854c3f87f84d88873910b8a9e65214 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_42212c1c91704b2190e66500eb508b71 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tobro-top-100'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f898dbb09e8648acaeb7847cf22f2f5b }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_42212c1c91704b2190e66500eb508b71 }}/appsvc/staticsite:${{ github.sha }}'